version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: es-logs-vol
        target: /var/log
      - type: volume
        source: es-data-vol
        target: /usr/share/elasticsearch/data
    networks:
      - net 
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es01:9200/
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: kibana-logs-vol
        target: /var/log
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - net 

volumes:
  es-data-vol:
  es-logs-vol:
  kibana-logs-vol:

networks:
   net:

